const products = [
    {
        id:1,
        name:'Tea',
        discription:'discription1',
        price:50
    },
    {
        id:2,
        name:'Coffee',
        discription:'discription2',
        price:70
    },
    {
        id:3,
        name:'Bread',
        discription:'discription3',
        price:30
    },
    {
        id:4,
        name:'Milk',
        discription:'discription4',
        price:25
    },
    {
        id:5,
        name:'Sugar',
        discription:'discription5',
        price:25
    },
]

module.exports={
products
}